version: '2'
services:
  node:
    build:
      context: .
      dockerfile: node.dockerfile
    ports:
      - "80:80"
    networks:
      - nodeapp-network
  mongodb:
    image: mongo
    container_name: mongo
    networks:
      - nodeapp-network
networks:
  nodeapp-network:
    driver: bridge
